### ISSUE TITLE
Why custom materials seem not work as well as the example image

### ISSUE THREAD

**Issue by gagadaxiao** [w84death/quake2-rtx-mapping#1]
Those self illuminate texture(such as train's lamp, roof lamp ), in RTX render mode they won't illuminate. I just place the BSP and WAL file in corresponding path, and type "map mansion" to run map. The game is Steam version. Many thanks

**Comment by beffio** [comment]
Yes, because this is for q2vkpt not the Quake II RTX by nvidia. They changed how the illumination works. I think  now it needs a real lights.
